### ISSUE TITLE
Nickname 是从哪里来

### ISSUE THREAD

**Issue by SyxP** [LocalizeLimbusCompany/LocalizeLimbusCompany#204]
在昨天的更新中，你们加这些信息。但这个信息在游戏中是没有的。可以不可以请解释一下这些信息的来源。谢谢。
During your translation update yesterday, you have added these nicknames. However, they are not to be found in the game files. Can you all explain where is the source of this information? Thank you.

https://github.com/LocalizeLimbusCompany/LocalizeLimbusCompany/blob/fc28ed08b6d9367cec5d8c2ac7aef8b429450d2f/Localize/NickName.json#L2251C1-L2509C6

**Comment by N071** [comment]
我们的信息更新来源于每周四更新后的客户端。我们使用自动化的更新流程，因此一般不会出现人为添加条目的情况，且全部条目也都直接来源于游戏文件。@Bright1192 是我们当中负责在游戏更新后即刻进行文本提取的维护者，您可以试着向他问询他当时进行更新工作的时间以及状况。他可以向您提供他使用的代码。
Our information is updated from the client side at each Thursday's update. We use an automated update process, so there are generally no entries added by humans, and all information is extracted right from the game files. @Bright1192 is one of our maintainers who is responsible for extracting text as soon as the game is updated, so you may try asking him when and how he was working on the update if you need. He can provide you with the code he used.

我们很清楚Project Moon官方不愿意出现解包内容泄露的情况，这在之前的公告中也被提到过。然而，作为一个社区组织，我们必须依靠自动化的流程才能处理如此多的工作量。由于人手上的不足，我们很难对获取到的信息进行审查和删减后再上传。
We are well aware of Project Moon's official reluctance to have a situation where unpacked content is leaked, which has been mentioned in previous announcements. However, as a community organization, we have to rely on automated processes in order to handle such a large workload. Due to the lack of manpower, it is difficult for us to review and redact the information we obtain before uploading it.

因此，我们从不对外提及此GitHub仓库的具体工作流程，以免其他人因为翻译之外的原因关注此仓库。
As a result, we never mention the exact workflow of this GitHub repository to the public so that others do not focus on it for reasons other than translation.

如果有其他想知道的事情，还请指出。
If you have any other concerns or requests, please let us know.

**Comment by SyxP** [comment]
对不起。 我以为这个文件不在游戏文件中，但我错了。
I'm sorry. I thought this file was not in the game files, but I was wrong.

**Comment by N071** [comment]
> 对不起。 我以为这个文件不在游戏文件中，但我错了。 I'm sorry. I thought this file was not in the game files, but I was wrong.

Never mind! We recall that you are the author of [Obiter Dicta](https://github.com/SyxP/ObiterDicta.jl)! Thak you for your work!!
